#Clase1 ML

In [40]:
#@title

# Python version
import sys
print('Python: {}'.format(sys.version))

import sklearn
print('sklearn: {}'.format(sklearn.__version__))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
sklearn: 0.19.1
scipy: 1.1.0
numpy: 1.14.3
matplotlib: 2.2.2
pandas: 0.23.0
sklearn: 0.19.1


In [41]:
#1numbers
3/2
3/float(2)
3%2
3.00//2.00
2**3
4**0.5
import math
math.sqrt(4)
2 + 10 * 10 + 3
(2+10) * (10+3)

156

In [42]:
#2Variables
a = 10
a =a + 10
a += 10
b = c = a
a,b,c = 1,2,"john"
my_dogs = 2
my_dogs = ['Sammy', 'Frankie']
del my_dogs

In [43]:
#3string
str = 'Hello World!'
print (str)          
print (str[0])       
print (str[2:5])     
print (str[2:])      
print (str * 2)      
print (str + "TEST")
str.upper()
str.split()
'Carlos: {}'.format(str)
print(" %s ,  %s" %(str,"I'm Carlos"))

print('I wrote %s programs today.' %3.75)
print('I wrote %d programs today.' %3.75)
print('I wrote %5.2f programs today.' %3.75)
print('First: %s, Second: %5.2f, Third: %r' %('hi!',3.1415,'bye!'))
print('The {2} {1} {0}'.format('fox','brown','quick'))
print('First Object: {a}, Second Object: {b}, Third Object: {c}'.format(a=1,b='Two',c=12.3))

print('{0:8} | {1:9}'.format('Fruit', 'Quantity'))
print('{0:8} | {1:9}'.format('Apples', 3.))
print('{0:8} | {1:9}'.format('Oranges', 10))

Hello World!
H
llo
llo World!
Hello World!Hello World!
Hello World!TEST
 Hello World! ,  I'm Carlos
I wrote 3.75 programs today.
I wrote 3 programs today.
I wrote  3.75 programs today.
First: hi!, Second:  3.14, Third: 'bye!'
The quick brown fox
First Object: 1, Second Object: Two, Third Object: 12.3
Fruit    | Quantity 
Apples   |       3.0
Oranges  |        10


In [44]:
#4Array list 
my_list = [1,2,3]
my_list = ['A string',23,100.232,'o']
my_list + ['new item']
my_list = my_list +['new item']
my_list.pop(0)
my_list.reverse()
my_list = [1,2,3]  #modifico para evitar error por tipo de variable
my_list.sort()
my_list * 2
my_list=[]
#my_list=array()

num_list = range(1, 101)
print(num_list[49])
type(num_list)
len(num_list)

new_list = [0, 1, 2, 3, 4, 5, 6]
new_list[2] = 2001;
new_list[2:5]
new_list[:3]
new_list[-2:]

list_1 = [1,2]
list_2 = [3, 4]
list_1+list_2
list_1.append(list_2)
[num*2 for num in list_1]

lst_1=[1,2,3]
lst_2=[4,5,6]
lst_3=[7,8,9]
matrix = [lst_1,lst_2,lst_3]
matrix[0][0]=8
print(matrix)



50
[[8, 2, 3], [4, 5, 6], [7, 8, 9]]


In [45]:
#4Dictionary


dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'}
print(dict['Name'])
dict.update()

d = {'a':10, 'b':20, 'c':30}
d['a']
d['b']=40
d.clear()
dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'}
dict.values()
dict.keys()
dict.items()
print(d)



locations = {'Sinan': ['Baltimore', 'MD'], 'Brandon': ['Arlington', 'VA']}
print(locations['Brandon'][1])

from numpy import random
data = {'a'+str(i) : random.randn() for i in range(7)}
print(data['a1'])
data


Manni
{}
VA


TypeError: 'str' object is not callable

In [46]:
#5Functions
def calc(a, b):
    return a + b
print(calc(2,3))


5


In [50]:
import numpy as np
# tipo de datos
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
#funciones basicas
miArray = np.arange(10) # Creamos un array de 0 a 9 separados de uno en uno
print (miArray) # Presentamos en pantalla el array creado
print (type(miArray))   #Comprobamos que es un ndarray
print (miArray.ndim )   # Consultamos el número de dimensiones
print (miArray.shape )  # Consultamos la dimensión
print (miArray.size )  # Consultamos la dimensión
print (miArray.dtype )  # Consultamos el tipo de elementos del array
print (miArray.itemsize )  # tamaño en bytes
print (miArray.data )  # Consultamos el buffer de memoria.

# array bidimensionales
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[2])
print(arr2d[0][2])
#arr2d[0,2]

#grupo de elementos
print((arr2d[:,1]))

# acesso con operaciones
print(arr2d[arr2d>4])

#fancy indexing
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

#seleccionar columnas en desorden
print (arr[[4, 3, 0, 6]])
#Using negative indices select rows from the end
print(arr[[-3, -5, -7]])

#reorganizar vectores
arr = np.arange(32).reshape((8, 4))
print(arr)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int64
8
[7 8 9]
3
[2 5 8]
[5 6 7 8 9]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
